[tools]
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:neovim/neovim" = "latest"
"npm:intelephense" = "latest"
"npm:typescript-language-server" = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
jq = "latest"
node = "lts"
rg = "latest"
tree-sitter = "latest"
