[tools]
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:neovim/neovim" = "latest"
"github:composer/composer" = { version = "latest", bin = "composer" }
"github:laravel/lsp" = { version = "latest", bin = "laravel-lsp" }
"npm:intelephense" = "latest"
"npm:typescript" = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
jq = "latest"
node = "lts"
rg = "latest"
tree-sitter = "latest"
